### ISSUE TITLE
Issue with the Kyma deployment: susaas-hana-deployer stuck in status pending

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/btp-cap-multitenant-saas#27] opened 2024-03-02 09:32 UTC
Hello,

I'm trying to get the application deployed to my BTP Free Tier Kyma environment in the region us10-001. Unfortunately it seems to be stuck in in the HANA deployment. Executing the helm install / upgrade results in:

```
Error: UPGRADE FAILED: pre-upgrade hooks failed: 1 error occurred:
        * timed out waiting for the condition
```

Looking at the susaas-hana-deployer pod in the Kyma Cockpit i see this warning:

```
0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 
No preemption victims found for incoming pod..
```

The log of this pod is completely empty. 

The list of created service instances looks OK:

![Screenshot of susaas Service Instances in the SAP BTP Cockpit](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/2639535/e551be55-cf38-452e-9855-4cc5e39b263e)

Also it seems that the HDI container for the t0 was created. But here I see a warning:

"This consuming option is out-of-date.[More details here](https://help.sap.com/docs/service-manager/sap-service-manager/consuming-sap-btp-services-in-kubernetes-with-sap-service-manager-broker-proxy-service-catalog)"

![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/2639535/0bd3c1d8-d1d8-46a6-8c01-2b39135065f0)

is an update needed here?

Looking forward for your input.

Best Regards
Gregor

**Comment by alperdedeoglu** [comment] 2024-03-07 08:19
Hi Gregor,
I think time for me to update CDS versions and do an end-2-end testing for both CF and Kyma.
Will keep here updated.

Best,
Alper

**Comment by thomaslaberge** [comment] 2024-04-08 22:24
Just tryed your branch upgrade and i have a similar error but the t0 is not being created
![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/152028187/c69bf817-fd64-4bb7-918d-a0e575f737a5)

**Comment by AjitKP91** [comment] 2024-04-09 04:41
@gregorwolf  Hi Gregor, 
issue:
0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 
No preemption victims found for incoming pod..

Can you check if you have enough CPU and Memory? 

Best, Ajit

**Comment by alperdedeoglu** [comment] 2024-04-30 12:07
@gregorwolf  closing this for the time being, since can not be reproduced. Please check if you have enough resource on your cluster before deploying, and the warning is something will be fixed by SAP BTP Operator colleagues.

**Closed by alperdedeoglu** 2024-04-30 12:07 UTC
